language: python
python:
  - "3.11"

os: windows

install:
  # Install Tesseract
  - |
    curl -L -o tesserocr-2.6.0-cp311-cp311-win_amd64.whl https://github.com/simonflueckiger/tesserocr-windows_build/releases/download/tesserocr-v2.6.0-tesseract-5.3.1/tesserocr-2.6.0-cp311-cp311-win_amd64.whl
    pip install tesserocr-2.6.0-cp311-cp311-win_amd64.whl

  # Install other dependencies
  - pip install -r requirements_win.txt

script:
  # Run your tests
  - pytest

  # Run Pylint
  - pylint poker
