os:
  - windows

language: shell

before_install:
  # Install Conda
  - choco install miniconda3 --params="/AddToPath:1"
  - source $HOME/miniconda3/etc/profile.d/conda.sh
  
install:
  # Create a Conda environment from environment.yml
  - conda env create --file environment.yml
  - conda activate my_env
  
script: pytest --log-cli-level=warning

after_success:
  - codecov

