name: poker311
channels:
  - conda-forge
  - defaults
dependencies:
  - autopep8=1.6.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.9.24
  - freetype=2.12.1
  - giflib=5.2.1
  - icu=70.1
  - jpeg=9e
  - lcms2=2.14
  - leptonica=1.82.0
  - lerc=4.0.0
  - libarchive=3.6.2
  - libcxx=15.0.7
  - libdeflate=1.14
  - libffi=3.4.2
  - libiconv=1.17
  - libpng=1.6.39
  - libtiff=4.4.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.10.3
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - lzo=2.10
  - ncurses=6.4
  - openjpeg=2.5.0
  - openssl=1.1.1t
  - pip=22.2.2
  - pthread-stubs=0.4
  - pycodestyle=2.8.0
  - python=3.11.0
  - python_abi=3.11
  - readline=8.2
  - setuptools=65.5.0
  - sqlite=3.40.1
  - tesseract=5.2.0
  - tesserocr=2.5.2
  - tk=8.6.12
  - toml=0.10.2
  - tzdata=2022g
  - wheel=0.37.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.10
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - absl-py==1.4.0
    - alabaster==0.7.13
    - altgraph==0.17.3
    - anyio==3.6.2
    - appdirs==1.4.4
    - appnope==0.1.3
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asteval==0.9.29
    - astroid==2.14.2
    - asttokens==2.2.1
    - astunparse==1.6.3
    - attrs==22.2.0
    - babel==2.12.1
    - backcall==0.2.0
    - beautifulsoup4==4.11.2
    - bleach==6.0.0
    - cachetools==5.3.0
    - cattrs==22.2.0
    - cffi==1.15.1
    - charset-normalizer==3.0.1
    - comm==0.1.2
    - contourpy==1.0.7
    - cycler==0.11.0
    - debugpy==1.6.6
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dill==0.3.6
    - dnspython==2.3.0
    - docutils==0.19
    - esbonio==0.16.1
    - et-xmlfile==1.1.0
    - executing==1.2.0
    - fastapi==0.92.0
    - fastjsonschema==2.16.3
    - flatbuffers==23.1.21
    - fonttools==4.38.0
    - fqdn==1.5.1
    - future==0.18.3
    - gast==0.4.0
    - google-auth==2.16.1
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.51.3
    - h5py==3.8.0
    - idna==3.4
    - imagesize==1.4.1
    - iniconfig==2.0.0
    - ipykernel==6.21.2
    - ipython==8.11.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.4
    - isoduration==20.11.0
    - isort==5.12.0
    - jax==0.4.4
    - jedi==0.18.2
    - jinja2==3.1.2
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter==1.0.0
    - jupyter-client==8.0.3
    - jupyter-console==6.6.2
    - jupyter-core==5.2.0
    - jupyter-events==0.6.3
    - jupyter-server==2.3.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.5
    - keras==2.12.0rc1
    - kiwisolver==1.4.4
    - lazy-object-proxy==1.9.0
    - libclang==15.0.6.1
    - lmfit==1.1.0
    - lsprotocol==2022.0.0a10
    - macholib==1.16.2
    - markdown==3.4.1
    - markupsafe==2.1.2
    - matplotlib==3.7.0
    - matplotlib-inline==0.1.6
    - mccabe==0.7.0
    - mistune==2.0.5
    - nbclassic==0.5.2
    - nbclient==0.7.2
    - nbconvert==7.2.9
    - nbformat==5.7.3
    - nest-asyncio==1.5.6
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - numexpr==2.8.4
    - numpy==1.23.5
    - oauthlib==3.2.2
    - opencv-python==4.7.0.72
    - openpyxl==3.1.1
    - opt-einsum==3.3.0
    - packaging==23.0
    - pandas==1.5.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.4.0
    - platformdirs==3.0.0
    - pluggy==1.0.0
    - prometheus-client==0.16.0
    - prompt-toolkit==3.0.38
    - protobuf==4.22.0
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pydantic==1.10.5
    - pydocstyle==6.3.0
    - pygls==1.0.1
    - pygments==2.14.0
    - pyinstaller==5.8.0
    - pyinstaller-hooks-contrib==2023.0
    - pylint==2.16.2
    - pymongo==4.3.3
    - pyobjc-core==9.0.1
    - pyobjc-framework-cocoa==9.0.1
    - pyobjc-framework-quartz==9.0.1
    - pyparsing==3.0.9
    - pyqt5==5.15.9
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.11.1
    - pyrsistent==0.19.3
    - pyspellchecker==0.7.1
    - pytesseract==0.3.10
    - pytest==7.2.1
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - pytz==2022.7.1
    - pyuserinput==0.1.11
    - pyyaml==6.0
    - pyzmq==25.0.0
    - qtconsole==5.4.0
    - qtpy==2.3.0
    - requests==2.28.2
    - requests-oauthlib==1.3.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rsa==4.9
    - scipy==1.10.1
    - seaborn==0.12.2
    - send2trash==1.8.0
    - six==1.16.0
    - sniffio==1.3.0
    - snowballstemmer==2.2.0
    - soupsieve==2.4
    - sphinx==6.1.3
    - sphinxcontrib-applehelp==1.0.4
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.1
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - stack-data==0.6.2
    - starlette==0.25.0
    - tensorboard==2.12.0
    - tensorboard-data-server==0.7.0
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.12.0rc0
    - tensorflow-estimator==2.12.0rc0
    - tensorflow-io-gcs-filesystem==0.31.0
    - termcolor==2.2.0
    - terminado==0.17.1
    - tinycss2==1.2.1
    - tomlkit==0.11.6
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.9.0
    - typeguard==2.13.3
    - typing-extensions==4.5.0
    - uncertainties==3.1.7
    - uri-template==1.2.0
    - urllib3==1.26.14
    - virtualbox==2.1.1
    - wcwidth==0.2.6
    - webcolors==1.12
    - webencodings==0.5.1
    - websocket-client==1.5.1
    - werkzeug==2.2.3
    - widgetsnbextension==4.0.5
    - wrapt==1.15.0
    - xlib==0.21
    - xlrd==2.0.1
